[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SUPABASE_PROJECT_ID = ""
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_PUBLISHABLE_KEY = ""

[context.deploy-preview.environment]
  VITE_SUPABASE_PROJECT_ID = ""
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_PUBLISHABLE_KEY = ""

[context.branch-deploy.environment]
  VITE_SUPABASE_PROJECT_ID = ""
  VITE_SUPABASE_URL = ""
  VITE_SUPABASE_PUBLISHABLE_KEY = ""
